dataset_name: "BPIC17"
intermediate_output_directory: "output_intermediate"
final_output_directory: "output_final"

# Task cluster settings
min_variant_freq: 10
num_clusters: 21
cluster_min_variant_length: 2
manual_clusters: { "m01": [ 1, 25, 107, 175, 186, 189, 191, 273, 295, 337, 346 ],
                   "m02": [ 2, 57, 87, 129, 180, 214, 217, 218 ],
                   "m03": [ 3, 33, 124, 165, 194, 212, 221, 271, 310, 317 ],
                   "m04": [ 7, 9, 45, 65, 150, 160, 228, 229, 231, 239, 270, 279, 326 ],
                   "m05": [ 20 ],
                   "m06": [ 50, 78, 145, 196 ],
                   "m07": [ 56, 269, 378 ] }
cluster_include_remainder: true
leftover_cluster: "T05"
clustering_description: "F10_C21_L2_M_R"

# Concept drift detection settings
window_sizes: [ 1 ]
penalties: [ 3 ]
process_drift_feature_sets: { task_relative: [ "count_per_task_relative" ],
                              task_variant_relative: [ "count_per_task_variant_relative" ] }
#process_drift_feature_sets: { task_relative: [ "count_per_task_relative" ],
#                              task_variant_relative: [ "count_per_task_variant_relative" ],
#                              activity_relative: [ "count_per_activity_relative" ],
#                              activity_handover_case_relative: [ "count_per_activity_handover_case_relative" ] }
#actor_drift_feature_sets: { tasks_relative: ["count_per_task_relative"] }
actor_drift_feature_sets: { task_handover_actor_relative: ["count_per_task_handover_actor_relative"] }
min_actor_frequency: 500
min_collab_frequency: 300

# Concept drift evaluation settings
cp_task_dict: { 1: [ "m04", "T03", "T07" ],
                2: [ "m01", "m03", "m04", "T01", "T02", "T11" ],
                3: [ "m02", "m04", "m05" ],
                4: [ "m05", "T11" ] }
cp_variant_dict: { 2: [ 4, 6, 8, 13 ],
                   3: [ 4, 27, 12, 43 ] }
