# Node properties
node_properties: {
    "A_Accepted+COMPLETE": ["square", "0.3", "0.3", "#8dd3c7"],
    "A_Cancelled+COMPLETE": ["square", "0.3", "0.3", "#ffffb3"],
    "A_Complete+COMPLETE": ["square", "0.3", "0.3", "#d9d9d9"],
    "A_Concept+COMPLETE": ["square", "0.3", "0.3", "#fb8072"],
    "A_Create Application+COMPLETE": ["square", "0.3", "0.3", "#fdb462"],
    "A_Denied+COMPLETE": ["square", "0.3", "0.3", "#80b1d3"],
    "A_Incomplete+COMPLETE": ["square", "0.3", "0.3", "#b3de69"],
    "A_Pending+COMPLETE": ["square", "0.3", "0.3", "#fccde5"],
    "A_Submitted+COMPLETE": ["square", "0.3", "0.3", "#bebada"],
    "A_Validating+COMPLETE": ["square", "0.3", "0.3", "#bc80bd"],
    "O_Accepted+COMPLETE": ["circle", "0.3", "0.3", "#1b9e77"],
    "O_Cancelled+COMPLETE": ["circle", "0.3", "0.3", "#e6ab02"],
    "O_Create Offer+COMPLETE": ["circle", "0.3", "0.3", "#d95f02"],
    "O_Created+COMPLETE": ["circle", "0.3", "0.3", "#7570b3"],
    "O_Refused+COMPLETE": ["circle", "0.3", "0.3", "#66a61e"],
    "O_Returned+COMPLETE": ["circle", "0.3", "0.3", "#e7298a"],
    "O_Sent (mail and online)+COMPLETE": ["circle", "0.3", "0.3", "#a6761d"],
    "O_Sent (online only)+COMPLETE": ["circle", "0.3", "0.3", "#666666"],
    "W_Assess potential fraud+SCHEDULE": ["rect", "0.15", "0.3", "#feedde"],
    "W_Assess potential fraud+START": ["rect", "0.15", "0.3", "#fdd0a2"],
    "W_Assess potential fraud+SUSPEND": ["rect", "0.15", "0.3", "#fdae6b"],
    "W_Assess potential fraud+RESUME": ["rect", "0.15", "0.3", "#fd8d3c"],
    "W_Assess potential fraud+WITHDRAW": ["rect", "0.15", "0.3", "#f16913"],
    "W_Assess potential fraud+ATE_ABORT": ["rect", "0.15", "0.3", "#d94801"],
    "W_Assess potential fraud+COMPLETE": ["rect", "0.15", "0.3", "#8c2d04"],
    "W_Call after offers+SCHEDULE": ["rect", "0.15", "0.3", "#eff3ff"],
    "W_Call after offers+START": ["rect", "0.15", "0.3", "#c6dbef"],
    "W_Call after offers+SUSPEND": ["rect", "0.15", "0.3", "#9ecae1"],
    "W_Call after offers+RESUME": ["rect", "0.15", "0.3", "#6baed6"],
    "W_Call after offers+WITHDRAW": ["rect", "0.15", "0.3", "#4292c6"],
    "W_Call after offers+ATE_ABORT": ["rect", "0.15", "0.3", "#2171b5"],
    "W_Call after offers+COMPLETE": ["rect", "0.15", "0.3", "#084594"],
    "W_Call incomplete files+SCHEDULE": ["rect", "0.15", "0.3", "#fee5d9"],
    "W_Call incomplete files+START": ["rect", "0.15", "0.3", "#fcbba1"],
    "W_Call incomplete files+SUSPEND": ["rect", "0.15", "0.3", "#fc9272"],
    "W_Call incomplete files+RESUME": ["rect", "0.15", "0.3", "#fb6a4a"],
    "W_Call incomplete files+ATE_ABORT": ["rect", "0.15", "0.3", "#cb181d"],
    "W_Call incomplete files+COMPLETE": ["rect", "0.15", "0.3", "#99000d"],
    "W_Complete application+SCHEDULE": ["rect", "0.15", "0.3", "#edf8e9"],
    "W_Complete application+START": ["rect", "0.15", "0.3", "#c7e9c0"],
    "W_Complete application+SUSPEND": ["rect", "0.15", "0.3", "#a1d99b"],
    "W_Complete application+RESUME": ["rect", "0.15", "0.3", "#74c476"],
    "W_Complete application+WITHDRAW": ["rect", "0.15", "0.3", "#41ab5d"],
    "W_Complete application+ATE_ABORT": ["rect", "0.15", "0.3", "#238b45"],
    "W_Complete application+COMPLETE": ["rect", "0.15", "0.3", "#005a32"],
    "W_Handle leads+SCHEDULE": ["rect", "0.15", "0.3", "#f7f7f7"],
    "W_Handle leads+START": ["rect", "0.15", "0.3", "#d9d9d9"],
    "W_Handle leads+SUSPEND": ["rect", "0.15", "0.3", "#bdbdbd"],
    "W_Handle leads+RESUME": ["rect", "0.15", "0.3", "#969696"],
    "W_Handle leads+WITHDRAW": ["rect", "0.15", "0.3", "#737373"],
    "W_Handle leads+ATE_ABORT": ["rect", "0.15", "0.3", "#525252"],
    "W_Handle leads+COMPLETE": ["rect", "0.15", "0.3", "#252525"],
    "W_Personal Loan collection+SCHEDULE": ["rect", "0.15", "0.3", "#b8e3dc"],
    "W_Personal Loan collection+START": ["rect", "0.15", "0.3", "#64c2b3"],
    "W_Personal Loan collection+SUSPEND": ["rect", "0.15", "0.3", "#378c7f"],
    "W_Personal Loan collection+RESUME": ["rect", "0.15", "0.3", "#276259"],
    "W_Shortened completion +SCHEDULE": ["rect", "0.15", "0.3", "#eedfba"],
    "W_Shortened completion +START": ["rect", "0.15", "0.3", "#dab869"],
    "W_Shortened completion +SUSPEND": ["rect", "0.15", "0.3", "#c99c31"],
    "W_Shortened completion +RESUME": ["rect", "0.15", "0.3", "#8a6b22"],
    "W_Validate application+SCHEDULE": ["rect", "0.15", "0.3", "#f2f0f7"],
    "W_Validate application+START": ["rect", "0.15", "0.3", "#dadaeb"],
    "W_Validate application+SUSPEND": ["rect", "0.15", "0.3", "#bcbddc"],
    "W_Validate application+RESUME": ["rect", "0.15", "0.3", "#9e9ac8"],
    "W_Validate application+ATE_ABORT": ["rect", "0.15", "0.3", "#6a51a3"],
    "W_Validate application+COMPLETE": ["rect", "0.15", "0.3", "#4a1486"]
}
